services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://sigec_user:${DB_PASSWORD}@db:3306/sigec_prod?allowPublicKeyRetrieval=true&useSSL=false
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: 24h
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: sigec_prod
      MYSQL_USER: sigec_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: