services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://app:red05e@db:3306/app_db"
      JWT_SECRET: jlkalaalajln267736982
      JWT_EXP: 24h
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app
      MYSQL_PASSWORD: red05e
      MYSQL_ROOT_PASSWORD: rootpassword123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: